### ISSUE TITLE
Error and A Question

### ISSUE THREAD

**Issue by YanTianlong-01** [hsiehjackson/Deep-Reinforcement-Learning-on-Atari-Games#14]
running the commend: python main.py --test_a2c --model_path=./model/best/a2c.cpt
Error:
Deep-Reinforcement-Learning-on-Atari-Games-master/mario_env.py", line 15, in <module>
    from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv
ModuleNotFoundError: No module named 'nes_py'

Another question I went to ask: where is the folder "./model" ? 
I can't find it on your project.

**Comment by hsiehjackson** [comment]
For `nes_py`: https://pypi.org/project/nes-py/
For `./model`: please first download model with my `download.sh`
